spring:
  application:
    name: Perfect Blend Suite API
    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY}
        access-token-expiration: 3600000
        refresh-token-expiration: 31536000000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

